import type { Product } from "@/types";
import {
	CATEGORY_AGUARDIENTE,
	CATEGORY_CERVEZA,
	CATEGORY_RON,
	CATEGORY_TEQUILA,
	CATEGORY_VINO,
	CATEGORY_VODKA,
	CATEGORY_WHISKY,
} from "./categories.mock";
import {
	SUPPLIER_BAVARIA,
	SUPPLIER_DIAGEO,
	SUPPLIER_LICORERA,
	SUPPLIER_PERNOD,
} from "./suppliers.mock";

const SEED_DATE = "2026-01-01T00:00:00.000Z";

export const productsMock: Product[] = [
	{
		id: "prod-1",
		sku: "CER-AGU-330",
		name: "Águila",
		brand: "Bavaria",
		categoryId: CATEGORY_CERVEZA,
		presentation: "Botella 330ml",
		volumeMl: 330,
		stock: { minStock: 100, warehouseLocation: "Estante A1" },
		pricing: { cost: 1800, retailPrice: 3000, wholesalePrice: 2400 },
		supplierId: SUPPLIER_BAVARIA,
		lastPurchaseDate: "2026-06-15",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-2",
		sku: "CER-CLU-330",
		name: "Club Colombia Dorada",
		brand: "Bavaria",
		categoryId: CATEGORY_CERVEZA,
		presentation: "Botella 330ml",
		volumeMl: 330,
		stock: { minStock: 80, warehouseLocation: "Estante A2" },
		pricing: { cost: 2200, retailPrice: 3800, wholesalePrice: 3000 },
		supplierId: SUPPLIER_BAVARIA,
		lastPurchaseDate: "2026-06-10",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-3",
		sku: "WHI-BUC-750",
		name: "Buchanan's 12 años",
		brand: "Buchanan's",
		categoryId: CATEGORY_WHISKY,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 10, warehouseLocation: "Estante B1" },
		pricing: { cost: 65000, retailPrice: 98000, wholesalePrice: 82000 },
		supplierId: SUPPLIER_DIAGEO,
		lastPurchaseDate: "2026-05-28",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-4",
		sku: "WHI-JWB-750",
		name: "Johnnie Walker Etiqueta Negra",
		brand: "Johnnie Walker",
		categoryId: CATEGORY_WHISKY,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 10, warehouseLocation: "Estante B2" },
		pricing: { cost: 72000, retailPrice: 110000, wholesalePrice: 92000 },
		supplierId: SUPPLIER_DIAGEO,
		lastPurchaseDate: "2026-05-20",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-5",
		sku: "RON-VIE-750",
		name: "Ron Viejo de Caldas 8 años",
		brand: "Viejo de Caldas",
		categoryId: CATEGORY_RON,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 15, warehouseLocation: "Estante C1" },
		pricing: { cost: 28000, retailPrice: 45000, wholesalePrice: 37000 },
		supplierId: SUPPLIER_LICORERA,
		lastPurchaseDate: "2026-06-01",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-6",
		sku: "RON-MED-1000",
		name: "Ron Medellín Añejo",
		brand: "Ron Medellín",
		categoryId: CATEGORY_RON,
		presentation: "Botella 1L",
		volumeMl: 1000,
		stock: { minStock: 12, warehouseLocation: "Estante C2" },
		pricing: { cost: 32000, retailPrice: 52000, wholesalePrice: 43000 },
		supplierId: SUPPLIER_LICORERA,
		lastPurchaseDate: "2026-04-18",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-7",
		sku: "VOD-SMI-750",
		name: "Smirnoff Vodka",
		brand: "Smirnoff",
		categoryId: CATEGORY_VODKA,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 15, warehouseLocation: "Estante D1" },
		pricing: { cost: 30000, retailPrice: 48000, wholesalePrice: 40000 },
		supplierId: SUPPLIER_DIAGEO,
		lastPurchaseDate: "2026-06-05",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-8",
		sku: "AGU-ANT-750",
		name: "Aguardiente Antioqueño Sin Azúcar",
		brand: "Aguardiente Antioqueño",
		categoryId: CATEGORY_AGUARDIENTE,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 30, warehouseLocation: "Estante E1" },
		pricing: { cost: 22000, retailPrice: 36000, wholesalePrice: 29000 },
		supplierId: SUPPLIER_LICORERA,
		lastPurchaseDate: "2026-06-20",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-9",
		sku: "VIN-CAS-750",
		name: "Casillero del Diablo Cabernet Sauvignon",
		brand: "Concha y Toro",
		categoryId: CATEGORY_VINO,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 10, warehouseLocation: "Estante F1" },
		pricing: { cost: 26000, retailPrice: 42000, wholesalePrice: 34000 },
		supplierId: SUPPLIER_PERNOD,
		lastPurchaseDate: "2026-05-30",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-10",
		sku: "TEQ-JOS-750",
		name: "Jose Cuervo Especial",
		brand: "Jose Cuervo",
		categoryId: CATEGORY_TEQUILA,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 8, warehouseLocation: "Estante G1" },
		pricing: { cost: 40000, retailPrice: 62000, wholesalePrice: 52000 },
		supplierId: SUPPLIER_PERNOD,
		lastPurchaseDate: "2026-04-02",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
];
