import type { Product } from "@/types";
import {
	CATEGORY_AGUARDIENTE,
	CATEGORY_CERVEZA,
	CATEGORY_RON,
	CATEGORY_TEQUILA,
	CATEGORY_VINO,
	CATEGORY_VODKA,
	CATEGORY_WHISKY,
} from "./categories.mock";

const SEED_DATE = "2026-01-01T00:00:00.000Z";

export const productsMock: Product[] = [
	{
		id: "prod-1",
		name: "Águila",
		brand: "Bavaria",
		categoryId: CATEGORY_CERVEZA,
		presentation: "Botella 330ml",
		volumeMl: 330,
		stock: { minStock: 100 },
		pricing: { cost: 1800, retailPrice: 3000 },
		lastPurchaseDate: "2026-06-15",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-2",
		name: "Club Colombia Dorada",
		brand: "Bavaria",
		categoryId: CATEGORY_CERVEZA,
		presentation: "Botella 330ml",
		volumeMl: 330,
		stock: { minStock: 80 },
		pricing: { cost: 2200, retailPrice: 3800 },
		lastPurchaseDate: "2026-06-10",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-3",
		name: "Buchanan's 12 años",
		brand: "Buchanan's",
		categoryId: CATEGORY_WHISKY,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 10 },
		pricing: { cost: 65000, retailPrice: 98000 },
		lastPurchaseDate: "2026-05-28",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-4",
		name: "Johnnie Walker Etiqueta Negra",
		brand: "Johnnie Walker",
		categoryId: CATEGORY_WHISKY,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 10 },
		pricing: { cost: 72000, retailPrice: 110000 },
		lastPurchaseDate: "2026-05-20",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-5",
		name: "Ron Viejo de Caldas 8 años",
		brand: "Viejo de Caldas",
		categoryId: CATEGORY_RON,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 15 },
		pricing: { cost: 28000, retailPrice: 45000 },
		lastPurchaseDate: "2026-06-01",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-6",
		name: "Ron Medellín Añejo",
		brand: "Ron Medellín",
		categoryId: CATEGORY_RON,
		presentation: "Botella 1L",
		volumeMl: 1000,
		stock: { minStock: 12 },
		pricing: { cost: 32000, retailPrice: 52000 },
		lastPurchaseDate: "2026-04-18",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-7",
		name: "Smirnoff Vodka",
		brand: "Smirnoff",
		categoryId: CATEGORY_VODKA,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 15 },
		pricing: { cost: 30000, retailPrice: 48000 },
		lastPurchaseDate: "2026-06-05",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-8",
		name: "Aguardiente Antioqueño Sin Azúcar",
		brand: "Aguardiente Antioqueño",
		categoryId: CATEGORY_AGUARDIENTE,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 30 },
		pricing: { cost: 22000, retailPrice: 36000 },
		lastPurchaseDate: "2026-06-20",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-9",
		name: "Casillero del Diablo Cabernet Sauvignon",
		brand: "Concha y Toro",
		categoryId: CATEGORY_VINO,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 10 },
		pricing: { cost: 26000, retailPrice: 42000 },
		lastPurchaseDate: "2026-05-30",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
	{
		id: "prod-10",
		name: "Jose Cuervo Especial",
		brand: "Jose Cuervo",
		categoryId: CATEGORY_TEQUILA,
		presentation: "Botella 750ml",
		volumeMl: 750,
		stock: { minStock: 8 },
		pricing: { cost: 40000, retailPrice: 62000 },
		lastPurchaseDate: "2026-04-02",
		active: true,
		createdAt: SEED_DATE,
		updatedAt: SEED_DATE,
	},
];
